### ISSUE TITLE
Definition errors compiling with 9.3.1 SDK

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [dbw/lwpp#2]
Trying to build a fresh download of lwpp against the 9.3.1 SDK and I have a few issues. Firstly the old classic:
error C1083: Cannot open include file: 'lwtimer.h': No such file or directory   

Followed by many of this ilk:
error C2039: 'itemColorRgba' : is not a member of 'st_LWInterfaceInfo'  
error C2039: 'itemColorRgba' : is not a member of 'st_LWInterfaceInfo'  
error C2039: 'itemIconScale' : is not a member of 'st_LWInterfaceInfo'  
error C2039: 'itemIconScale' : is not a member of 'st_LWInterfaceInfo'  

Preprocessor definition set to LW_SDK=93;...

Could be my fault (as usual :P) but who knows.

**Comment by Anti-Distinctlyminty** [comment]
NB: I just download the repositor and didn't check out as I don't know how to use git yet :/ 

In interface.h I'm guessing the

```
if (globPtr) return globPtr->itemIconScale(item);
```

at lin 451 needs commenting out or removing?

In image.h line 138 I added the #if to the functions introduced in 95

```
#if LW_SDK >= 95
    int  getAttr ( LWImageParam tag, void* data )
    {
      return globPtr->getAttr(pixmap, tag, data);
    }
    int  getMakerNote ( LWMakerNote tag, void* data )
    {
      return globPtr->getMakerNote(pixmap, tag, data);
    }
#endif
```

**Comment by Anti-Distinctlyminty** [comment]
lw_version.h is missing

```
#define LWPP_NODEEDITORFUNCS_GLOBAL         "NodeEditorFuncs"
```

and 

```
#define LWPP_COLORACTIVATEFUNC_GLOBAL       "Color Picker"
```

in the LW_SDK == 93 section

**Comment by lightwolf** [comment]
I was actually thinking about removing anything that is pre-10 at one point in time.
